services:
  jupyter:
    build: .
    container_name: jupyter_container
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=flighttracker123
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - my_network

  postgres:
    image: postgres:18
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - my_network

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin_container
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "8080:80"
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      networks:
        - my_network
      depends_on:
        - postgres

networks:
  my_network:

volumes:
  postgres_data: