[project]
name = "flight-tracker-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chacha Marwa", email = "chachamarwa003@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
flight-tracker-pipeline = "flight_tracker_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
